use std::collections::HashMap;

use lazy_static::lazy_static;

use crate::region::Region;

use super::{booster_group::BoosterGroup, options::GameOptions, r#type::GameType};

lazy_static! {
    pub static ref GAME_TO_NPC: HashMap<GameType, &'static str> = HashMap::from([
        (GameType::Build, "Master Builders"),
        (GameType::Draw, "Draw My Thing"),
        (GameType::Micro, "Micro Battles"),
        (GameType::MixedArcade, "Mixed Arcade"),
        (GameType::TurfWars, "Turf Wars"),
        (GameType::SpeedBuilders, "Speed Builders"),
        (GameType::HideSeek, "Block Hunt"),
        (GameType::CakeWars4, "Cake Wars"),
        (GameType::SurvivalGames, "Survival Games"),
        (GameType::Skywars, "Skywars"),
        (GameType::Bridges, "The Bridges"),
        (GameType::MineStrike, "Mine-Strike"),
        (GameType::Smash, "Super Smash Mobs"),
        (GameType::Clans, "Clans"),
        (GameType::ClansHub, "ClansHub"),
    ]);
    pub static ref GAME_TO_BOOSTER_GROUP: HashMap<GameType, BoosterGroup> = HashMap::from([
        (GameType::Micro, BoosterGroup::Arcade),
        (GameType::Draw, BoosterGroup::Draw_My_Thing),
        (GameType::MineStrike, BoosterGroup::Arcade),
        (GameType::TurfWars, BoosterGroup::Arcade),
        (GameType::Build, BoosterGroup::Master_Builders),
        (GameType::SpeedBuilders, BoosterGroup::Speed_Builders),
        (GameType::HideSeek, BoosterGroup::Block_Hunt),
        (GameType::CakeWarsDuos, BoosterGroup::Cake_Wars),
        (GameType::CakeWars4, BoosterGroup::Cake_Wars),
        (GameType::SurvivalGames, BoosterGroup::Survival_Games),
        (GameType::SurvivalGamesTeams, BoosterGroup::Survival_Games),
        (GameType::Skywars, BoosterGroup::Skywars),
        (GameType::SkywarsTeams, BoosterGroup::Skywars),
        (GameType::Bridges, BoosterGroup::Bridges),
        (GameType::MineStrike, BoosterGroup::MineStrike),
        (GameType::Smash, BoosterGroup::Smash_Mobs),
        (GameType::SmashTeams, BoosterGroup::Smash_Mobs),
        (GameType::ChampionsDominate, BoosterGroup::Champions),
        (GameType::ChampionsCTF, BoosterGroup::Champions),
        (GameType::NanoGames, BoosterGroup::Nano_Games)
    ]);
    pub static ref GAME_TO_PLAYER_COUNT: HashMap<GameType, (u8, u8)> = HashMap::from([
        (GameType::Micro, (8, 16)),
        (GameType::MixedArcade, (8, 24)),
        (GameType::Draw, (5, 8)),
        (GameType::Build, (8, 12)),
        (GameType::TurfWars, (8, 16)),
        (GameType::SpeedBuilders, (4, 8)),
        (GameType::HideSeek, (12, 24)),
        (GameType::CakeWarsDuos, (10, 16)),
        (GameType::CakeWars4, (10, 16)),
        (GameType::SurvivalGames, (12, 24)),
        (GameType::SurvivalGamesTeams, (12, 24)),
        (GameType::Skywars, (8, 12)),
        (GameType::SkywarsTeams, (8, 12)),
        (GameType::Bridges, (20, 40)),
        (GameType::MineStrike, (8, 16)),
        (GameType::Smash, (4, 6)),
        (GameType::SmashTeams, (4, 6)),
        (GameType::ChampionsDominate, (8, 10)),
        (GameType::ChampionsCTF, (10, 16)),
        (GameType::Clans, (1, 50)),
        (GameType::ClansHub, (1, 50)),
    ]);
    pub static ref GAME_TO_SERVER_PREFIX: HashMap<GameType, &'static str> = HashMap::from([
        (GameType::Micro, "MB"),
        (GameType::MixedArcade, "MIN"),
        (GameType::Draw, "DMT"),
        (GameType::Build, "BLD"),
        (GameType::TurfWars, "TF"),
        (GameType::SpeedBuilders, "SB"),
        (GameType::HideSeek, "BH"),
        (GameType::CakeWarsDuos, "CW2"),
        (GameType::CakeWars4, "CW4"),
        (GameType::SurvivalGames, "HG"),
        (GameType::SurvivalGamesTeams, "SG2"),
        (GameType::Skywars, "SKY"),
        (GameType::SkywarsTeams, "SKY2"),
        (GameType::Bridges, "BR"),
        (GameType::MineStrike, "MS"),
        (GameType::Smash, "SSM"),
        (GameType::SmashTeams, "SSM2"),
        (GameType::ChampionsDominate, "DOM"),
        (GameType::ChampionsCTF, "CTF"),
        (GameType::Clans, "Clans"),
        (GameType::ClansHub, "ClansHub"),
        (GameType::NanoGames, "NANO"),
        (GameType::Retro, "RETRO")
    ]);
    pub static ref SERVER_PREFIX_TO_GAME: HashMap<&'static str, GameType> = HashMap::from([
        ("MB", GameType::Micro),
        ("MIN", GameType::MixedArcade),
        ("DMT", GameType::Draw),
        ("BLD", GameType::Build),
        ("TF", GameType::TurfWars),
        ("SB", GameType::SpeedBuilders),
        ("BH", GameType::HideSeek),
        ("CW2", GameType::CakeWarsDuos),
        ("CW4", GameType::CakeWars4),
        ("HG", GameType::SurvivalGames),
        ("SG2", GameType::SurvivalGamesTeams),
        ("SKY", GameType::Skywars),
        ("SKY2", GameType::SkywarsTeams),
        ("BR", GameType::Bridges),
        ("MS", GameType::MineStrike),
        ("SSM", GameType::Smash),
        ("SSM2", GameType::SmashTeams),
        ("DOM", GameType::ChampionsDominate),
        ("CTF", GameType::ChampionsCTF),
        ("Clans", GameType::Clans),
        ("ClansHub", GameType::ClansHub),
        ("NANO", GameType::NanoGames),
        ("RETRO", GameType::Retro)
    ]);
    pub static ref GAME_TO_TEAM_SERVER: HashMap<GameType, GameType> = HashMap::from([
        (GameType::Skywars, GameType::SkywarsTeams),
        (GameType::SurvivalGames, GameType::SurvivalGamesTeams),
        (GameType::Smash, GameType::SmashTeams),
        (GameType::ChampionsDominate, GameType::ChampionsCTF),
        (GameType::CakeWars4, GameType::CakeWarsDuos),
    ]);
    pub static ref CUSTOM_GAME_OPTIONS: HashMap<GameType, GameOptions> = HashMap::from([
        (
            GameType::Clans,
            GameOptions {
                prefix: "Clans".to_string(),
                staff_only: false,
                whitelist: false,
                host: None,
                min_players: 1,
                max_players: 50,
                port_section: 25565, // changes automatically
                arcade_group: false,
                world_zip: "clans.zip".to_string(),
                plugin: "Clans.jar".to_string(),
                config_path: "plugins/Clans".to_string(),
                pvp: false,
                tournament: false,
                tournament_points: false,
                games: None,
                server_type: "dedicated".to_string(),
                add_no_cheat: false,
                add_world_edit: true,
                team_rejoin: false,
                team_auto_join: false,
                team_force_balance: false,
                game_auto_start: false,
                game_timeout: true,
                game_voting: false,
                map_voting: false,
                reward_gems: true,
                reward_items: true,
                reward_stats: true,
                reward_achievements: true,
                hotbar_inventory: false,
                hotbar_hub_clock: true,
                player_kick_idle: false,
                team_server: None,
                booster_group: None,
                npc_name: Some("Clans".to_string()),
                resource_pack: None,
                region: Region::US,
                portal_bottom_corner_location: None,
                portal_top_corner_location: None
            }
        ),
        (
            GameType::ClansHub,
            GameOptions {
                prefix: "ClansHub".to_string(),
                staff_only: false,
                whitelist: false,
                host: None,
                min_players: 1,
                max_players: 50,
                port_section: 25565, // changes automatically
                arcade_group: false,
                world_zip: "clanshub.zip".to_string(),
                plugin: "ClansHub.jar".to_string(),
                config_path: "plugins/ClansHub".to_string(),
                pvp: false,
                tournament: false,
                tournament_points: false,
                games: None,
                server_type: "dedicated".to_string(),
                add_no_cheat: false,
                add_world_edit: true,
                team_rejoin: false,
                team_auto_join: false,
                team_force_balance: false,
                game_auto_start: false,
                game_timeout: true,
                game_voting: true,
                map_voting: true,
                reward_gems: true,
                reward_items: true,
                reward_stats: true,
                reward_achievements: true,
                hotbar_inventory: false,
                hotbar_hub_clock: true,
                player_kick_idle: true,
                team_server: None,
                booster_group: None,
                npc_name: Some("Clans".to_string()),
                resource_pack: None,
                region: Region::US,
                portal_bottom_corner_location: None,
                portal_top_corner_location: None,
            },
        )
    ]);
}
