[package]
name = "plex_redis_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.14"
redis = "0.25.4"
serde = {version = "1.0.204", features = ["derive"]}
